
import { Listing, Transaction, ChatContact, User, SystemConfig, AuditLog } from './types';

// --- SYSTEM CONFIGURATION DEFAULTS ---
export const DEFAULT_SYSTEM_CONFIG: SystemConfig = {
  fees: {
    platformPercentage: 10,
    fixedFeeEur: 2.00,
    superHubberDiscount: 2,
  },
  referral: {
    isActive: true,
    bonusAmount: 10.00, // 10 Euro bonus per friend
  },
  cancellationPolicies: [
    { 
      id: 'flexible', 
      label: 'Flessibile', 
      description: 'Rimborso 100% fino a 24 ore prima.', 
      refundPercentage: 100, 
      cutoffHours: 24,
      color: 'green'
    },
    { 
      id: 'moderate', 
      label: 'Moderata', 
      description: 'Rimborso 100% fino a 5 giorni prima.', 
      refundPercentage: 100, 
      cutoffHours: 120,
      color: 'yellow'
    },
    { 
      id: 'strict', 
      label: 'Rigida', 
      description: 'Rimborso 50% fino a 7 giorni prima.', 
      refundPercentage: 50, 
      cutoffHours: 168,
      color: 'red'
    }
  ],
  completenessThreshold: 70,
  superHubberMinRating: 4.7,
  // NEW CMS DEFAULTS
  cms: {
    heroTitle: "Noleggia qualsiasi cosa, ovunque tu sia.",
    heroSubtitle: "La piattaforma di sharing economy sicura e flessibile.",
    footerText: "© 2024 Renthubber Italia S.r.l.",
    faq: [
        { question: "Come funziona la cauzione?", answer: "Viene bloccata temporaneamente e rilasciata dopo il check-out." }
    ],
    termsUrl: "#",
    privacyUrl: "#"
  },
  // NEW BRAND DEFAULTS
  brand: {
    primaryColor: "#0D414B",
    logoUrl: "", // Use default if empty
    faviconUrl: "",
    heroImageUrl: "https://www.transparenttextures.com/patterns/cubes.png"
  },
  // NEW NOTIFICATION DEFAULTS
  notifications: {
    emailEnabled: true,
    pushEnabled: true,
    templates: {
      bookingConfirmed: "La tua prenotazione #{{id}} è confermata! Prepara le valigie.",
      bookingCancelled: "La prenotazione #{{id}} è stata cancellata. Il rimborso è in arrivo.",
      payoutProcessed: "Abbiamo inviato il tuo bonifico di €{{amount}}. Arriverà in 2-3 giorni lavorativi."
    }
  }
};

// --- USERS ---

export const DEMO_RENTER: User = {
  id: 'renter1',
  name: 'Mario Rossi',
  email: 'mario.renter@demo.com',
  avatar: 'https://ui-avatars.com/api/?name=Mario+Rossi&background=random',
  rating: 4.5,
  isSuperHubber: false,
  role: 'renter',
  roles: ['renter'], 
  status: 'active',
  renterBalance: 45.50, 
  hubberBalance: 0, 
  referralCode: 'MARIO24'
};

export const DEMO_HUBBER: User = {
  id: 'hubber1',
  name: 'Giulia Bianchi',
  email: 'giulia.hubber@demo.com',
  avatar: 'https://ui-avatars.com/api/?name=Giulia+Bianchi&background=random',
  rating: 5.0,
  reviewCount: 156,
  isSuperHubber: true,
  role: 'hubber',
  roles: ['renter', 'hubber'], 
  status: 'active',
  renterBalance: 10.00, 
  hubberBalance: 1240.50, 
  referralCode: 'GIULIAVIP',
  hubberSince: '2021-05-15T10:00:00Z',
  bio: "Ciao! Sono Giulia, architetto e appassionata di fotografia. Amo condividere i miei spazi e la mia attrezzatura con creativi e professionisti. Sono precisa, puntuale e tengo molto alla cura dei miei oggetti.",
  languages: ['Italiano', 'Inglese', 'Spagnolo'],
  responseTime: 'entro un\'ora',
  responseRate: 98,
  verifications: {
    email: true,
    phone: true,
    identity: true
  },
  bankDetails: {
    accountHolderName: 'Giulia',
    accountHolderSurname: 'Bianchi',
    iban: 'IT60X0542811101000000123456',
    bankName: 'Intesa Sanpaolo',
    bicSwift: 'BCITITMM'
  }
};

export const DEMO_ADMIN: User = {
  id: 'admin1',
  name: 'Admin System',
  email: 'admin@renthubber.com',
  avatar: 'https://ui-avatars.com/api/?name=Admin+System&background=000&color=fff',
  rating: 5.0,
  isSuperHubber: false,
  role: 'admin',
  roles: ['admin', 'renter', 'hubber'], 
  status: 'active',
  renterBalance: 0,
  hubberBalance: 0,
  referralCode: 'ADMIN'
};

// --- MOCK DATA ---

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  { id: 'log1', adminName: 'Admin System', action: 'Update Fee', target: 'Global', timestamp: '2023-10-25 10:30', details: 'Commissioni portate al 10%' },
  { id: 'log2', adminName: 'Admin System', action: 'Ban User', target: 'user_x99', timestamp: '2023-10-24 14:15', details: 'Violazione termini ripetuta' },
  { id: 'log3', adminName: 'Moderator A', action: 'Suspend Listing', target: 'listing_3', timestamp: '2023-10-23 09:00', details: 'Foto non conformi' },
];

// --- HELPER FOR MOCK LISTINGS ---
const mockOwner = (name: string, isSuper: boolean = false): User => ({
    ...DEMO_HUBBER,
    id: `owner_${name.replace(/\s/g, '')}`,
    name: name,
    avatar: `https://ui-avatars.com/api/?name=${name}&background=random`,
    isSuperHubber: isSuper,
    rating: isSuper ? 4.9 : (3.5 + Math.random() * 1.5)
});

export const MOCK_LISTINGS: Listing[] = [
  // --- OGGETTI (15 Items) ---
  {
    id: 'obj1',
    title: 'Trapano Professionale Bosch 18V',
    category: 'oggetto',
    subCategory: 'Fai-da-te',
    description: 'Trapano avvitatore professionale a batteria, perfetto per lavori di fai-da-te o ristrutturazioni. Include due batterie e valigetta.',
    price: 15,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=800&q=80'],
    location: 'Milano, MI',
    coordinates: { lat: 45.4642, lng: 9.1900 },
    rating: 4.8,
    reviewCount: 24,
    owner: DEMO_HUBBER, 
    features: ['2 Batterie incluse', 'Punte incluse', 'Valigetta'],
    rules: ['Restituire pulito', 'Documento richiesto'],
    deposit: 50,
    status: 'published',
    cancellationPolicy: 'flexible',
    reviews: [{ id: 'r1', userId: 'u2', userName: 'Luca B.', rating: 5, comment: 'Ottimo attrezzo.', date: '2023-10-10' }],
    zoneDescription: 'Zona Isola, servita da M5.',
    manualBadges: ['Offerta']
  },
  {
    id: 'obj2',
    title: 'Sony Alpha 7 III + Obiettivo 24-70mm',
    category: 'oggetto',
    subCategory: 'Elettronica',
    description: 'Fotocamera mirrorless full-frame. Perfetta per videoclip e fotografia professionale. Include scheda SD 128GB.',
    price: 45,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=800&q=80'],
    location: 'Roma, RM',
    coordinates: { lat: 41.9028, lng: 12.4964 },
    rating: 4.9,
    reviewCount: 42,
    owner: mockOwner('Alessandro V.', true),
    features: ['Scheda SD', 'Borsa', 'Caricatore'],
    rules: ['Attenzione alla lente', 'Penale per danni'],
    deposit: 500,
    status: 'published',
    cancellationPolicy: 'strict',
    reviews: [],
    manualBadges: ['Novità']
  },
  {
    id: 'obj3',
    title: 'Drone DJI Mavic 3 Cine',
    category: 'oggetto',
    subCategory: 'Elettronica',
    description: 'Drone professionale per riprese cinematografiche. Registrazione Apple ProRes, doppia fotocamera. Richiesto patentino.',
    price: 120,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1579829366248-204fe8413f31?auto=format&fit=crop&w=800&q=80'],
    location: 'Torino, TO',
    coordinates: { lat: 45.0703, lng: 7.6869 },
    rating: 5.0,
    reviewCount: 15,
    owner: mockOwner('Video Service snc', true),
    features: ['3 Batterie', 'Filtri ND', 'Controller Smart'],
    rules: ['Patentino obbligatorio', 'No volo su folla'],
    deposit: 800,
    status: 'published',
    cancellationPolicy: 'strict',
    reviews: [],
    manualBadges: ['Premium']
  },
  {
    id: 'obj4',
    title: 'Console DJ Pioneer XDJ-XZ',
    category: 'oggetto',
    subCategory: 'Musica',
    description: 'Sistema all-in-one professionale per DJ a 4 canali. Perfetto per feste private, matrimoni o piccoli club.',
    price: 100,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1598653222000-6b7b7a552625?auto=format&fit=crop&w=800&q=80'],
    location: 'Milano, MI',
    coordinates: { lat: 45.47, lng: 9.20 },
    rating: 4.7,
    reviewCount: 8,
    owner: mockOwner('Matteo DJ'),
    features: ['Case rigido', 'Cavi inclusi'],
    rules: ['No drink vicino alla console'],
    deposit: 400,
    status: 'published',
    cancellationPolicy: 'moderate',
    reviews: [],
  },
  {
    id: 'obj5',
    title: 'Mountain Bike Elettrica Specialized',
    category: 'oggetto',
    subCategory: 'Sport',
    description: 'E-MTB Turbo Levo, taglia L. Batteria da 700Wh, autonomia eccellente per gite in montagna.',
    price: 60,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?auto=format&fit=crop&w=800&q=80'],
    location: 'Trento, TN',
    coordinates: { lat: 46.07, lng: 11.12 },
    rating: 4.9,
    reviewCount: 30,
    owner: mockOwner('Trentino Rent', true),
    features: ['Casco incluso', 'Caricabatterie rapido'],
    rules: ['Lavaggio finale incluso'],
    deposit: 200,
    status: 'published',
    cancellationPolicy: 'flexible',
    reviews: [],
    manualBadges: ['Amato dagli ospiti']
  },
  {
    id: 'obj6',
    title: 'Proiettore 4K BenQ',
    category: 'oggetto',
    subCategory: 'Elettronica',
    description: 'Proiettore Home Cinema 4K HDR. Ideale per serate cinema, presentazioni aziendali o gaming.',
    price: 35,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80'],
    location: 'Bologna, BO',
    coordinates: { lat: 44.49, lng: 11.34 },
    rating: 4.6,
    reviewCount: 12,
    owner: mockOwner('Marco S.'),
    features: ['Cavo HDMI 5m', 'Telecomando'],
    rules: ['Maneggiare con cura'],
    deposit: 150,
    status: 'published',
    cancellationPolicy: 'flexible',
    reviews: [],
  },
  {
    id: 'obj7',
    title: 'Set Luci Fotografiche Godox',
    category: 'oggetto',
    subCategory: 'Elettronica',
    description: 'Kit completo con 2 softbox, stativi e flash da studio SK400II. Perfetto per ritratti e still life.',
    price: 40,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1527011046414-4781f1f94f8c?auto=format&fit=crop&w=800&q=80'],
    location: 'Firenze, FI',
    coordinates: { lat: 43.76, lng: 11.25 },
    rating: 5.0,
    reviewCount: 5,
    owner: mockOwner('Elena Photo'),
    features: ['Borsa trasporto', 'Trigger wireless'],
    rules: [],
    deposit: 100,
    status: 'published',
    cancellationPolicy: 'flexible',
    reviews: [],
  },
  {
    id: 'obj8',
    title: 'Idropulitrice Karcher K5',
    category: 'oggetto',
    subCategory: 'Fai-da-te',
    description: 'Idropulitrice potente per pulizia esterni, auto, muri e pavimenti. Pressione regolabile.',
    price: 25,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80'],
    location: 'Padova, PD',
    coordinates: { lat: 45.40, lng: 11.87 },
    rating: 4.4,
    reviewCount: 18,
    owner: mockOwner('Luca Garage'),
    features: ['Lancia rotante', 'Detergente incluso'],
    rules: ['Svuotare acqua dopo uso'],
    deposit: 50,
    status: 'published',
    cancellationPolicy: 'flexible',
    reviews: [],
  },
  {
    id: 'obj9',
    title: 'Tenda da Tetto per Auto',
    category: 'oggetto',
    subCategory: 'Campeggio',
    description: 'Tenda da tetto rigida universale, si monta in 5 minuti. Materasso comodo incluso. Perfetta per weekend on the road.',
    price: 50,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?auto=format&fit=crop&w=800&q=80'],
    location: 'Roma, RM',
    coordinates: { lat: 41.89, lng: 12.51 },
    rating: 4.9,
    reviewCount: 22,
    owner: mockOwner('Adventure Time', true),
    features: ['Impermeabile', 'Scaletta telescopica'],
    rules: ['Aiuto montaggio incluso'],
    deposit: 300,
    status: 'published',
    cancellationPolicy: 'moderate',
    reviews: [],
    manualBadges: ['Estate 2024']
  },
  {
    id: 'obj10',
    title: 'Cassa JBL PartyBox 310',
    category: 'oggetto',
    subCategory: 'Musica',
    description: 'Speaker Bluetooth potente con luci ed effetti sonori. Batteria a lunga durata, ideale per feste in giardino o spiaggia.',
    price: 35,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
    location: 'Napoli, NA',
    coordinates: { lat: 40.85, lng: 14.26 },
    rating: 4.8,
    reviewCount: 40,
    owner: mockOwner('Ciro Sound'),
    features: ['Microfono incluso', 'Ruote per trasporto'],
    rules: ['Non immergere in acqua'],
    deposit: 100,
    status: 'published',
    cancellationPolicy: 'flexible',
    reviews: [],
  },
  {
    id: 'obj11',
    title: 'Generatore di Corrente 3KW',
    category: 'oggetto',
    subCategory: 'Fai-da-te',
    description: 'Generatore a benzina silenziato inverter. Ideale per mercatini, campeggio o lavori in zone senza elettricità.',
    price: 40,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1581092335397-9583eb92d232?auto=format&fit=crop&w=800&q=80'],
    location: 'Bari, BA',
    coordinates: { lat: 41.11, lng: 16.87 },
    rating: 4.5,
    reviewCount: 10,
    owner: mockOwner('Edil Noleggi'),
    features: ['Tanica benzina vuota', 'Cavi adattatori'],
    rules: ['Restituire con pieno'],
    deposit: 150,
    status: 'published',
    cancellationPolicy: 'moderate',
    reviews: [],
  },
  {
    id: 'obj12',
    title: 'Tavola da Surf Longboard 9\'',
    category: 'oggetto',
    subCategory: 'Sport',
    description: 'Longboard classico, stabile e facile da usare. Perfetto per principianti o giornate con onde piccole.',
    price: 20,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1531722569936-825d3dd91b15?auto=format&fit=crop&w=800&q=80'],
    location: 'Cagliari, CA',
    coordinates: { lat: 39.22, lng: 9.12 },
    rating: 5.0,
    reviewCount: 7,
    owner: mockOwner('Surf House'),
    features: ['Leash incluso', 'Sacca trasporto'],
    rules: ['Attenzione alle pinne'],
    deposit: 100,
    status: 'published',
    cancellationPolicy: 'flexible',
    reviews: [],
  },
  {
    id: 'obj13',
    title: 'Videocamera GoPro Hero 11 Black',
    category: 'oggetto',
    subCategory: 'Elettronica',
    description: 'Action cam top di gamma. Stabilizzazione HyperSmooth 5.0, video 5.3K. Impermeabile fino a 10m.',
    price: 25,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=800&q=80'],
    location: 'Genova, GE',
    coordinates: { lat: 44.40, lng: 8.94 },
    rating: 4.7,
    reviewCount: 33,
    owner: mockOwner('Digital Rent'),
    features: ['Asta selfie', '2 Batterie', 'Case subacqueo'],
    rules: [],
    deposit: 150,
    status: 'published',
    cancellationPolicy: 'flexible',
    reviews: [],
  },
  {
    id: 'obj14',
    title: 'Saldatrice Inverter',
    category: 'oggetto',
    subCategory: 'Fai-da-te',
    description: 'Saldatrice compatta e leggera a elettrodo. Perfetta per piccoli lavori di carpenteria metallica.',
    price: 30,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=800&q=80'],
    location: 'Verona, VR',
    coordinates: { lat: 45.43, lng: 10.99 },
    rating: 4.2,
    reviewCount: 4,
    owner: mockOwner('Giovanni Fabbro'),
    features: ['Maschera inclusa', 'Spazzola'],
    rules: ['Solo per esperti'],
    deposit: 100,
    status: 'published',
    cancellationPolicy: 'moderate',
    reviews: [],
  },
  {
    id: 'obj15',
    title: 'Playstation 5 + 2 Joypad',
    category: 'oggetto',
    subCategory: 'Elettronica',
    description: 'Console PS5 con lettore disco. Include FIFA 24, Call of Duty e Gran Turismo 7.',
    price: 25,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&q=80'],
    location: 'Milano, MI',
    coordinates: { lat: 45.45, lng: 9.18 },
    rating: 4.9,
    reviewCount: 55,
    owner: mockOwner('GameRent Milano', true),
    features: ['Giochi preinstallati', 'Cavo HDMI 2.1'],
    rules: ['Non resettare console'],
    deposit: 200,
    status: 'published',
    cancellationPolicy: 'flexible',
    reviews: [],
  },

  // --- SPAZI (15 Items) ---
  {
    id: 'spc1',
    title: 'Loft Open Space per Eventi',
    category: 'spazio',
    subCategory: 'Eventi',
    description: 'Splendido loft industriale di 150mq, ideale per mostre, shooting fotografici o eventi aziendali. Luce naturale incredibile.',
    price: 50,
    priceUnit: 'ora',
    images: ['https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80'],
    location: 'Torino, TO',
    coordinates: { lat: 45.0703, lng: 7.6869 },
    rating: 4.9,
    reviewCount: 112,
    owner: DEMO_HUBBER,
    features: ['Wi-Fi', 'Proiettore', 'Bagno', 'Cucina', 'Aria Condizionata'],
    rules: ['No feste notturne', 'Max 50 persone'],
    deposit: 200,
    status: 'published',
    cancellationPolicy: 'moderate',
    reviews: [],
    maxGuests: 50,
    openingHours: '08:00 - 22:00',
    zoneDescription: 'Quartiere Vanchiglia, pieno di locali e arte.',
    manualBadges: ['Top Location']
  },
  {
    id: 'spc2',
    title: 'Sala Riunioni Centro Direzionale',
    category: 'spazio',
    subCategory: 'Ufficio',
    description: 'Sala meeting professionale per 10 persone. Schermo 65", lavagna, acqua e caffè inclusi. Reception.',
    price: 25,
    priceUnit: 'ora',
    images: ['https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=800&q=80'],
    location: 'Milano, MI',
    coordinates: { lat: 45.48, lng: 9.19 },
    rating: 4.6,
    reviewCount: 45,
    owner: mockOwner('Office Solutions', true),
    features: ['WiFi Fibra', 'Stampante', 'Reception'],
    rules: ['Silenzio nei corridoi'],
    deposit: 0,
    status: 'published',
    cancellationPolicy: 'flexible',
    reviews: [],
    maxGuests: 10,
    openingHours: '09:00 - 19:00'
  },
  {
    id: 'spc3',
    title: 'Garage Sicuro Centro Storico',
    category: 'spazio',
    subCategory: 'Parcheggio',
    description: 'Box auto privato, coperto e videosorvegliato. Accesso 24/7 con telecomando. Adatto a SUV.',
    price: 20,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1486006920555-c77dcf18193c?auto=format&fit=crop&w=800&q=80'],
    location: 'Firenze, FI',
    coordinates: { lat: 43.77, lng: 11.24 },
    rating: 4.8,
    reviewCount: 88,
    owner: mockOwner('Lorenzo P.'),
    features: ['Videosorveglianza', 'Automatico', 'Illuminato'],
    rules: ['No deposito merci infiammabili'],
    deposit: 50,
    status: 'published',
    cancellationPolicy: 'flexible',
    reviews: [],
    openingHours: '24/7'
  },
  {
    id: 'spc4',
    title: 'Studio Fotografico Limbo',
    category: 'spazio',
    subCategory: 'Studio',
    description: 'Studio fotografico con limbo bianco 4x4m. Altezza 3.5m. Include stativi e camerino trucco.',
    price: 40,
    priceUnit: 'ora',
    images: ['https://images.unsplash.com/photo-1534234828563-025511d92463?auto=format&fit=crop&w=800&q=80'],
    location: 'Roma, RM',
    coordinates: { lat: 41.88, lng: 12.48 },
    rating: 4.9,
    reviewCount: 34,
    owner: mockOwner('Cinecittà Rent'),
    features: ['Camerino', 'Bagno', 'Zona relax'],
    rules: ['Lasciare pulito il limbo (penale verniciatura)'],
    deposit: 100,
    status: 'published',
    cancellationPolicy: 'moderate',
    reviews: [],
    maxGuests: 8,
    openingHours: '09:00 - 21:00'
  },
  {
    id: 'spc5',
    title: 'Magazzino Temporaneo 20mq',
    category: 'spazio',
    subCategory: 'Magazzino',
    description: 'Spazio deposito asciutto e sicuro al piano terra. Ideale per traslochi o archivio. Accesso furgoni.',
    price: 10,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80'],
    location: 'Bologna, BO',
    coordinates: { lat: 44.50, lng: 11.30 },
    rating: 4.5,
    reviewCount: 12,
    owner: mockOwner('Deposito Facile'),
    features: ['Piano terra', 'Carico/Scarico facile'],
    rules: ['No sostanze pericolose'],
    deposit: 50,
    status: 'published',
    cancellationPolicy: 'flexible',
    reviews: [],
    openingHours: '08:00 - 20:00'
  },
  {
    id: 'spc6',
    title: 'Terrazza Panoramica per Aperitivi',
    category: 'spazio',
    subCategory: 'Eventi',
    description: 'Terrazza privata al 7° piano con vista duomo. Arredata con divanetti e piante. Perfetta per compleanni o eventi corporate.',
    price: 150,
    priceUnit: 'ora',
    images: ['https://images.unsplash.com/photo-1519750783826-e2420f4d687f?auto=format&fit=crop&w=800&q=80'],
    location: 'Milano, MI',
    coordinates: { lat: 45.46, lng: 9.19 },
    rating: 5.0,
    reviewCount: 20,
    owner: mockOwner('Skyline Events', true),
    features: ['Vista panoramica', 'Impianto audio', 'Bar'],
    rules: ['Musica bassa dopo le 23', 'Max 30 persone'],
    deposit: 500,
    status: 'published',
    cancellationPolicy: 'strict',
    reviews: [],
    maxGuests: 30,
    openingHours: '18:00 - 24:00',
    manualBadges: ['Esclusivo']
  },
  {
    id: 'spc7',
    title: 'Postazione Coworking Open',
    category: 'spazio',
    subCategory: 'Ufficio',
    description: 'Scrivania in open space luminoso. Inclusi: sedia ergonomica, wifi 1Gbps, cucina condivisa, caffè illimitato.',
    price: 15,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=800&q=80'],
    location: 'Torino, TO',
    coordinates: { lat: 45.06, lng: 7.67 },
    rating: 4.7,
    reviewCount: 65,
    owner: mockOwner('Impact Hub TO'),
    features: ['WiFi', 'Caffè', 'Stampante'],
    rules: ['Silenzio', 'Pulire scrivania'],
    deposit: 0,
    status: 'published',
    cancellationPolicy: 'flexible',
    reviews: [],
    maxGuests: 1,
    openingHours: '08:30 - 19:30'
  },
  {
    id: 'spc8',
    title: 'Sala Prove Insonorizzata',
    category: 'spazio',
    subCategory: 'Studio',
    description: 'Sala prove musicale di 30mq completamente insonorizzata. Batteria, amplificatori e impianto voce inclusi.',
    price: 18,
    priceUnit: 'ora',
    images: ['https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=800&q=80'],
    location: 'Roma, RM',
    coordinates: { lat: 41.91, lng: 12.52 },
    rating: 4.8,
    reviewCount: 150,
    owner: mockOwner('Music Box'),
    features: ['Batteria', 'Ampli chitarra', 'Climatizzatore'],
    rules: ['Non fumare', 'Rispettare orari'],
    deposit: 0,
    status: 'published',
    cancellationPolicy: 'flexible',
    reviews: [],
    maxGuests: 6,
    openingHours: '10:00 - 24:00'
  },
  {
    id: 'spc9',
    title: 'Giardino Privato per Feste Bimbi',
    category: 'spazio',
    subCategory: 'Eventi',
    description: 'Ampio giardino di 200mq recintato. Giochi per bambini, gazebo e barbecue disponibili.',
    price: 80,
    priceUnit: 'ora',
    images: ['https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=800&q=80'],
    location: 'Monza, MB',
    coordinates: { lat: 45.58, lng: 9.27 },
    rating: 4.9,
    reviewCount: 28,
    owner: mockOwner('Famiglia Rossi'),
    features: ['Barbecue', 'Altalena', 'Tavoli'],
    rules: ['Pulire dopo uso', 'Cani ammessi'],
    deposit: 100,
    status: 'published',
    cancellationPolicy: 'moderate',
    reviews: [],
    maxGuests: 40,
    openingHours: '10:00 - 20:00'
  },
  {
    id: 'spc10',
    title: 'Cantina Vini Climatizzata',
    category: 'spazio',
    subCategory: 'Magazzino',
    description: 'Spazio in cantina professionale per stoccaggio vino. Temperatura e umidità controllate. Accesso esclusivo.',
    price: 50,
    priceUnit: 'settimana',
    images: ['https://images.unsplash.com/photo-1516594915697-87eb3b1c14ea?auto=format&fit=crop&w=800&q=80'],
    location: 'Verona, VR',
    coordinates: { lat: 45.44, lng: 10.98 },
    rating: 5.0,
    reviewCount: 5,
    owner: mockOwner('Cantine Venete', true),
    features: ['Climatizzato', 'Allarme', 'Assicurazione'],
    rules: ['Solo vino imbottigliato'],
    deposit: 200,
    status: 'published',
    cancellationPolicy: 'strict',
    reviews: [],
    openingHours: 'Su appuntamento'
  },
  {
    id: 'spc11',
    title: 'Pop-up Store Vetrina su Strada',
    category: 'spazio',
    subCategory: 'Eventi',
    description: 'Negozio temporaneo in zona di forte passaggio. Vetrina luce, illuminazione a binario, piccolo magazzino sul retro.',
    price: 200,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80'],
    location: 'Milano, MI',
    coordinates: { lat: 45.47, lng: 9.18 },
    rating: 4.6,
    reviewCount: 14,
    owner: mockOwner('Retail Spaces'),
    features: ['Vetrina', 'WiFi', 'Camerino'],
    rules: ['Minimo 3 giorni', 'Assicurazione richiesta'],
    deposit: 1000,
    status: 'published',
    cancellationPolicy: 'strict',
    reviews: [],
    maxGuests: 20,
    openingHours: '09:00 - 21:00',
    manualBadges: ['Business']
  },
  {
    id: 'spc12',
    title: 'Cucina Industriale per Showcooking',
    category: 'spazio',
    subCategory: 'Studio',
    description: 'Cucina professionale attrezzata per corsi di cucina, showcooking o preparazione catering. 4 fuochi, forni, abbattitore.',
    price: 60,
    priceUnit: 'ora',
    images: ['https://images.unsplash.com/photo-1556910103-1c02745a30bf?auto=format&fit=crop&w=800&q=80'],
    location: 'Parma, PR',
    coordinates: { lat: 44.80, lng: 10.32 },
    rating: 4.9,
    reviewCount: 22,
    owner: mockOwner('Food Lab'),
    features: ['Attrezzatura completa', 'Lavastoviglie', 'Celle frigo'],
    rules: ['HACCP richiesto', 'Pulizia profonda finale'],
    deposit: 300,
    status: 'published',
    cancellationPolicy: 'moderate',
    reviews: [],
    maxGuests: 12,
    openingHours: '08:00 - 23:00'
  },
  {
    id: 'spc13',
    title: 'Ufficio Privato 2 Posti',
    category: 'spazio',
    subCategory: 'Ufficio',
    description: 'Piccolo ufficio privato per 2 persone. Ideale per startup o freelance che necessitano di privacy.',
    price: 40,
    priceUnit: 'giorno',
    images: ['https://images.unsplash.com/photo-1504384308090-c54be3852d33?auto=format&fit=crop&w=800&q=80'],
    location: 'Bari, BA',
    coordinates: { lat: 41.12, lng: 16.86 },
    rating: 4.5,
    reviewCount: 9,
    owner: mockOwner('Co-Bari'),
    features: ['Chiavi private', 'Scrivanie', 'Cassettiere'],
    rules: [],
    deposit: 50,
    status: 'published',
    cancellationPolicy: 'flexible',
    reviews: [],
    maxGuests: 2,
    openingHours: '24/7'
  },
  {
    id: 'spc14',
    title: 'Sala Yoga / Palestra Privata',
    category: 'spazio',
    subCategory: 'Studio',
    description: 'Sala con parquet e specchi, ideale per lezioni di yoga, pilates o personal training.',
    price: 25,
    priceUnit: 'ora',
    images: ['https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80'],
    location: 'Rimini, RN',
    coordinates: { lat: 44.06, lng: 12.56 },
    rating: 4.8,
    reviewCount: 31,
    owner: mockOwner('Wellness Studio'),
    features: ['Tappetini', 'Casse Bluetooth', 'Spogliatoio'],
    rules: ['No scarpe', 'Asciugamano obbligatorio'],
    deposit: 0,
    status: 'published',
    cancellationPolicy: 'flexible',
    reviews: [],
    maxGuests: 10,
    openingHours: '07:00 - 22:00'
  },
  {
    id: 'spc15',
    title: 'Spazio Esterno per Deposito Camper',
    category: 'spazio',
    subCategory: 'Parcheggio',
    description: 'Posto auto scoperto in area recintata privata in campagna. Ideale per camper o barche.',
    price: 60,
    priceUnit: 'mese',
    images: ['https://images.unsplash.com/photo-1626125345510-470341d1159c?auto=format&fit=crop&w=800&q=80'],
    location: 'Pisa, PI',
    coordinates: { lat: 43.72, lng: 10.40 },
    rating: 4.7,
    reviewCount: 18,
    owner: mockOwner('Agriturismo Il Pino'),
    features: ['Recintato', 'Accesso su richiesta', 'Economico'],
    rules: ['No pernottamento'],
    deposit: 50,
    status: 'published',
    cancellationPolicy: 'flexible',
    reviews: [],
    openingHours: '08:00 - 20:00'
  }
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  { id: 't1', date: '2023-10-24', amount: 45.00, description: 'Noleggio Sony Alpha', type: 'debit', walletType: 'renter' },
  { id: 't2', date: '2023-10-20', amount: 120.00, description: 'Incasso Loft Eventi', type: 'credit', walletType: 'hubber' },
  { id: 't3', date: '2023-10-15', amount: 10.00, description: 'Bonus Invito Amico', type: 'credit', walletType: 'renter' },
  { id: 't4', date: '2023-10-10', amount: 250.00, description: 'Prelievo su IBAN', type: 'debit', walletType: 'hubber' },
];

export const MOCK_CONTACTS: ChatContact[] = [
  { id: 'c1', name: 'Marco Rossi', avatar: 'https://ui-avatars.com/api/?name=Marco+Rossi', lastMessage: 'Ciao, il trapano è disponibile per domani?', unreadCount: 1, lastMessageTime: '10:30' },
  { id: 'c2', name: 'Giulia Bianchi', avatar: 'https://ui-avatars.com/api/?name=Giulia+Bianchi', lastMessage: 'Grazie per aver lasciato il loft in ordine!', unreadCount: 0, lastMessageTime: 'Ieri' },
];
